### ISSUE TITLE
RuntimeError: More keyword list entries (7) than format specifiers (6)

### ISSUE THREAD

**Issue by timmartin19** [psf/requests#4164]
_Disclaimer_ I'm not sure if this is actually an issue with the requests library.  Additionally, we have had significant trouble consistently reproducing this issue.

We are running a Flask app in AWS ECS.  In order to [retrieve task credentials|http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html] in an ECS task, we need to send a request to `http://169.254.170.2/v2/credentials?task_id=:task_id`.  Instead we're getting the very strange error in the title from `_socket.getaddrinfo`.  

## Expected Result

We get a response (or at least a reasonable error message)

## Actual Result

*Note* Despite our best efforts, we have not been able to reliably reproduce this.  It seems to start happening after a few hours.

```
ERROR in exceptions: More keyword list entries (7) than format specifiers (6)	
Traceback (most recent call last):	  
File "/home/app/dashboard-api/dashboard_api/views/pilot_group.py", line 167, in  
   req = requests.get('http://169.254.170.2' + cred_uri)	  
File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 72, in get	 
   return request('get', url, params=params, **kwargs)	  
File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 58, in request	 
   return session.request(method=method, url=url, **kwargs)	  
File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 502, in request	
    resp = self.send(prep, **send_kwargs)	  
File "/usr/local/lib/python3.5/site-packages/raven/breadcrumbs.py", line 297, in send	 
   resp = real_send(self, request, *args, **kwargs)	  
File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 612, in send	
    r = adapter.send(request, **kwargs)	  
File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 440, in send	 
   timeout=timeout	  
File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen	 
   chunked=chunked)	  
File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 356, in _make_request	 
   conn.request(method, url, **httplib_request_kw)	  
   File "/usr/local/lib/python3.5/http/client.py", line 1106, in request	 
      self._send_request(method, url, body, headers)	  
File "/usr/local/lib/python3.5/http/client.py", line 1151, in _send_request	 
   self.endheaders(body)	  
File "/usr/local/lib/python3.5/http/client.py", line 1102, in endheaders	 
   self._send_output(message_body)	  
File "/usr/local/lib/python3.5/http/client.py", line 934, in _send_output	 
   self.send(msg)	  
File "/usr/local/lib/python3.5/http/client.py", line 877, in send	 
   self.connect()	  
File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 166, in connect	 
   conn = self._new_conn()	   
File "/usr/local/lib/python3.5/site-packages/urllib3/connection.py", line 141, in _new_conn	  
  (self.host, self.port), self.timeout, **extra_kw)	  
File "/usr/local/lib/python3.5/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
File "/usr/local/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
RuntimeError: More keyword list entries (7) than format specifiers (6)
```

## Reproduction Steps

We are having a lot of trouble consistently reproducing this but this is the code that triggers it when it happens.  Typically it starts failing after a few hours.  Originally we thought it was an issue with botocore (and potentially refreshing credentials) so we added the following code but we kept getting the same error.

```python
import requests

# The request path from an environment variable populated by ECS
cred_uri = os.environ.get('AWS_CONTAINER_CREDENTIALS_RELATIVE_URI')
if cred_uri:
    resp = requests.get('http://169.254.170.2' + cred_uri)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "implementation": {
    "name": "CPython",
    "version": "3.5.2"
  },
  "platform": {
    "release": "4.9.27-moby",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.1"
  },
  "system_ssl": {
    "version": "100020bf"
  },
  "urllib3": {
    "version": "1.21.1"
  },
  "using_pyopenssl": false
}
```

Other interesting information:

Running on AWS EC2 Container Service (ECS)
Docker v: 17.03.1-ce
ECS agent version: 1.14.3
We're using [raven-python|https://github.com/getsentry/raven-python] which hooks into requests to log the results.
uwsgi is running it in a Flask app with multi processing and multithreading.

**Comment by Lukasa** [comment]
This error strikes me as being a follow-on. I suspect some exception is happening in or around getaddrinfo, and that error is being masked because an attempt is made to format a string that goes awry. The exception itself seems to be happening in the stdlib though. I'd recommend seeing if you can use strace or something similar to spot what is going on in the Python standard library there. One way or another, this error seems to be coming out of the low-level C code in the interpreter.

**Comment by nateprewitt** [comment]
Resolving as this is quite old and we haven't had any follow up providing more information to investigate.
