### ISSUE TITLE
Requests returns an error on Google App Engine when upgrading from requests==2.10.0 to the latest versions

### ISSUE THREAD

**Issue by interpegasus** [psf/requests#5042]
Hi, My app works fine with version 2.10.0, when connecting to flickr API, however, when upgrading to the latest version of requests, google app engine returns the error below. Any help will be appreciated on how to use the latest version of this library on Google app engine. Thanks.

`ConnectionError: HTTPSConnectionPool(host='api.flickr.com', port=443): Max retries exceeded with url: /services/rest/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x2a63f8ef7d50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))`

## Expected Result
The process should complete succesfully as in version 2.10.0

## Actual Result

```
Internal Server Error: /api/queuetask/flickr (/base/data/home/apps/s~pegasus7/20190405t190338.417285350479019321/sitepackages/prod/django/core/handlers/exception.py:135)
Traceback (most recent call last):
  File "/base/data/home/apps/s~arturopegasus7/20190405t190338.417285350479019321/sitepackages/prod/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/base/data/home/apps/s~arturopegasus7/20190405t190338.417285350479019321/sitepackages/prod/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/base/data/home/apps/s~arturopegasus7/20190405t190338.417285350479019321/sitepackages/prod/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/base/data/home/apps/s~arturopegasus7/20190405t190338.417285350479019321/backend/views.py", line 206, in task_sync_flickr
    SyncData.flickr()
  File "/base/data/home/apps/s~arturopegasus7/20190405t190338.417285350479019321/backend/utils/sync_data.py", line 756, in flickr
    user = flickr_api.test.login()
  File "/base/data/home/apps/s~arturopegasus7/20190405t190338.417285350479019321/sitepackages/prod/flickr_api/reflection.py", line 294, in static_call
    r = method_call.call_api(method=flickr_method, **method_args)
  File "/base/data/home/apps/s~arturopegasus7/20190405t190338.417285350479019321/sitepackages/prod/flickr_api/method_call.py", line 124, in call_api
    resp = requests.post(request_url, args)
  File "/base/data/home/apps/s~arturopegasus7/20190405t190338.417285350479019321/sitepackages/prod/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/base/data/home/apps/s~arturopegasus7/20190405t190338.417285350479019321/sitepackages/prod/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/base/data/home/apps/s~arturopegasus7/20190405t190338.417285350479019321/sitepackages/prod/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/base/data/home/apps/s~arturopegasus7/20190405t190338.417285350479019321/sitepackages/prod/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/base/data/home/apps/s~arturopegasus7/20190405t190338.417285350479019321/sitepackages/prod/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='api.flickr.com', port=443): Max retries exceeded with url: /services/rest/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x2a90be9751d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
```

## Reproduction Steps

```python
import flickr_api
import requests
import requests_toolbelt.adapters.appengine
flickr_api.set_keys(api_key=FLICKR_KEY, api_secret=FLICKR_SEC)
flickr_api.set_auth_handler('./backend/utils/flickr_verifier')
time.sleep(1)
user = flickr_api.test.login()
```

## System Information

    $ python -m requests.help
```
{
  "chardet": {
    "version": "3.0.4"
  }, 
  "cryptography": {
    "version": ""
  }, 
  "idna": {
    "version": "2.8"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.15"
  }, 
  "platform": {
    "release": "18.5.0", 
    "system": "Darwin"
  }, 
  "pyOpenSSL": {
    "openssl_version": "", 
    "version": null
  }, 
  "requests": {
    "version": "2.21.0"
  }, 
  "system_ssl": {
    "version": "1000210f"
  }, 
  "urllib3": {
    "version": "1.24.1"
  }, 
  "using_pyopenssl": false
}

```

**Comment by abranjith** [comment]
what's the underlying requests call that you are making ? Exact code would help

**Comment by sethmlarson** [comment]
From the error message I don't think there's anything urllib3 or Requests can do here. DNS is failing, we're not in control of that sort of issue. Closing this as not a defect in Requests.
