### ISSUE TITLE
When i try install pygame i get error

### ISSUE THREAD

**Issue by omurkaya** [psf/requests#5094]
When i try install py game terminal give me error

Windows 10

Python 3.7.3

`
Exception:
Traceback (most recent call last):
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\cli\base_command.py", line 179, in main
    status = self.run(options, args)
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\commands\install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\operations\prepare.py", line 269, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\req\req_install.py", line 196, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\index.py", line 639, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\index.py", line 610, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\index.py", line 743, in _get_pages
    page = _get_html_page(location, session=self.session)
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\index.py", line 229, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\index.py", line 177, in _get_html_response
    "Cache-Control": "max-age=0",
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_vendor\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_internal\download.py", line 403, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_vendor\requests\sessions.py", line 524, in request
    prep.url, proxies, stream, verify, cert
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_vendor\requests\sessions.py", line 700, in merge_environment_settings
    env_proxies = get_environ_proxies(url, no_proxy=no_proxy)
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_vendor\requests\utils.py", line 761, in get_environ_proxies
    if should_bypass_proxies(url, no_proxy=no_proxy):
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_vendor\requests\utils.py", line 745, in should_bypass_proxies
    bypass = proxy_bypass(parsed.hostname)
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_vendor\requests\utils.py", line 95, in proxy_bypass
    return proxy_bypass_registry(host)
  File "C:\Users\KAYA\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pip\_vendor\requests\utils.py", line 61, in proxy_bypass_registry
    'ProxyEnable')[0])
ValueError: invalid literal for int() with base 10: '0.0.0.0:0000'`

**Comment by godra9** [comment]
#up

**Comment by LuRsT** [comment]
@omurkaya It'd be easier if you used ` ``` ` instead of just the single `. It makes the block of "code" more readable.

**Comment by godra9** [comment]
I reinstall windows its fixed xD

**Comment by LuRsT** [comment]
Could you close this PR then @omurkaya?
