### ISSUE TITLE
Bug - Error "Connection aborted BadStatusLine" under proxy network

### ISSUE THREAD

**Issue by Kenith** [psf/requests#5155]
Hello All,

Our company network is under proxy, and not trust all the certificates.
We have a url need to check the status: https://www.anz.com/anzwealthinsights/default.asp

The url is redirected 2 times:
https://www.anz.com/anzwealthinsights/default.asp
-> redirect-1: http://www.anzwealthinsights.anz.com/?cid=anz:private
-> redirect-2: https://www.anzwealthinsights.anz.com/?cid=anz:private

When we trying to request the url, the error `ConnectionError: ('Connection aborted.', BadStatusLine("''",))` happens. And I can confirm that it happens at redirect-2.

Note: If we don't under company network, and request the url, all fine.

Would you please fix the issue?

Here is the info you need:
Python: 2.7
Requests: 2.22.0
Network: Under proxy, and not trust any certificate
Code:
```
headers = { 'User-Agent': 'Mozilla/5.0 (Windows NT 6.0; WOW64; rv:24.0) Gecko/20100101 Firefox/24.0' }

requests.get('https://www.anz.com/anzwealthinsights/default.asp', verify=False, proxies={'http': '127.0.0.1:3128', 'https': '127.0.0.1:3128'}, headers=headers)

/Library/Python/2.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 247, in resolve_redirects
    **adapter_kwargs
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

requests.get('https://www.anz.com/anzwealthinsights/default.asp', verify=False)

/Library/Python/2.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/Library/Python/2.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
<Response [200]>
```

**Comment by nateprewitt** [comment]
Hi @Kenith, given the situation you’re describing, this is an issue with the proxy. It’s either continuing to send data after we believe a Response is complete, or not returning a properly formatted http Response at all.

If you’re able to get this working correctly with curl, it *may* be an issue with urllib3 or httplib in cPython but you’d need to raise an issue there.
