### ISSUE TITLE
python-requests master now broken on Python 2.7

### ISSUE THREAD

**Issue by sjlongland** [psf/requests#5175]
Summary.

## Expected Result

Working `python-requests`

## Actual Result

```
build	26-Aug-2019 10:21:30	Traceback (most recent call last):
build	26-Aug-2019 10:21:30	  File "/usr/bin/widesky-tagset-manager", line 11, in <module>
build	26-Aug-2019 10:21:30	    load_entry_point('widesky-toolkit==0.3.0', 'console_scripts', 'widesky-tagset-manager')()
build	26-Aug-2019 10:21:30	  File "/usr/lib/python2.7/dist-packages/widesky_toolkit/tagset/tagset_manager.py", line 91, in main
build	26-Aug-2019 10:21:30	    ), args)
build	26-Aug-2019 10:21:30	  File "/usr/lib/python2.7/dist-packages/widesky_toolkit/tagset/operations/base_op.py", line 28, in perform_op
build	26-Aug-2019 10:21:30	    op = cls(connection, args)
build	26-Aug-2019 10:21:30	  File "/usr/lib/python2.7/dist-packages/widesky_toolkit/tagset/operations/install_tagset.py", line 29, in __init__
build	26-Aug-2019 10:21:30	    super(InstallTagsetOp, self).__init__(connection, args)
build	26-Aug-2019 10:21:30	  File "/usr/lib/python2.7/dist-packages/widesky_toolkit/tagset/operations/base_op.py", line 51, in __init__
build	26-Aug-2019 10:21:30	    self._repo = TagSetRepository.get_instance(args)
build	26-Aug-2019 10:21:30	  File "/usr/lib/python2.7/dist-packages/widesky_toolkit/tagset/repo/repository.py", line 81, in get_instance
build	26-Aug-2019 10:21:30	    return implementation(parsed_uri, args)
build	26-Aug-2019 10:21:30	  File "/usr/lib/python2.7/dist-packages/widesky_toolkit/tagset/repo/webdav.py", line 45, in __init__
build	26-Aug-2019 10:21:30	    verify_ssl=verify, cert=cert)
build	26-Aug-2019 10:21:30	  File "/usr/lib/python2.7/dist-packages/easywebdav/__init__.py", line 5, in connect
build	26-Aug-2019 10:21:30	    return Client(*args, **kwargs)
build	26-Aug-2019 10:21:30	  File "/usr/lib/python2.7/dist-packages/easywebdav/client.py", line 83, in __init__
build	26-Aug-2019 10:21:30	    self.session = requests.session()
build	26-Aug-2019 10:21:30	  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 774, in session
build	26-Aug-2019 10:21:30	    return Session()
build	26-Aug-2019 10:21:30	  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 422, in __init__
build	26-Aug-2019 10:21:30	    super().__init__()
build	26-Aug-2019 10:21:30	TypeError: super() takes at least 1 argument (0 given)
```

## Reproduction Steps

```
stuartl@vk4msl-ws:~$ docker run --rm -ti debian:stretch bash
Unable to find image 'debian:stretch' locally
stretch: Pulling from library/debian
9cc2ad81d40d: Pull complete 
Digest: sha256:94a5c04481bb50a4f34ebbb105e39388700202a6e34cb41b9b9afdaca854567c
Status: Downloaded newer image for debian:stretch
root@4f09a4eb7e2a:/# apt-get update && apt-get install -y python-pip git
… wait for package installation…
root@4f09a4eb7e2a:/# pip2 install git+http://github.com/psf/requests.git         
Collecting git+http://github.com/psf/requests.git
  Cloning http://github.com/psf/requests.git to /tmp/pip-OMHRQ6-build
Collecting certifi>=2017.4.17 (from requests==2.22.0)
  Downloading https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl (157kB)
    100% |################################| 163kB 320kB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.22.0)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |################################| 143kB 315kB/s 
Collecting idna<2.9,>=2.5 (from requests==2.22.0)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |################################| 61kB 1.9MB/s 
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests==2.22.0)
  Downloading https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl (150kB)
    100% |################################| 153kB 4.8MB/s 
Installing collected packages: certifi, chardet, idna, urllib3, requests
  Found existing installation: idna 2.2
    Not uninstalling idna at /usr/lib/python2.7/dist-packages, outside environment /usr
  Running setup.py install for requests ... done
Successfully installed certifi-2019.6.16 chardet-3.0.4 idna-2.8 requests-2.22.0 urllib3-1.25.3
root@4f09a4eb7e2a:/# python2
Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.session()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 774, in session
    return Session()
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 422, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
>>> 
```

## System Information

```
root@4f09a4eb7e2a:/# python -m requests.help
{
  "chardet": {
    "version": "3.0.4"
  }, 
  "cryptography": {
    "version": ""
  }, 
  "idna": {
    "version": "2.8"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.13"
  }, 
  "platform": {
    "release": "4.15.0-55-generic", 
    "system": "Linux"
  }, 
  "pyOpenSSL": {
    "openssl_version": "", 
    "version": null
  }, 
  "requests": {
    "version": "2.22.0"
  }, 
  "system_ssl": {
    "version": "101000bf"
  }, 
  "urllib3": {
    "version": "1.25.3"
  }, 
  "using_pyopenssl": false
}
```

**Comment by nateprewitt** [comment]
This should be resolved with 09fd857. Thanks @sjlongland!
