### ISSUE TITLE
can not run single test using setup.py test

### ISSUE THREAD

**Issue by magus0219** [psf/requests#5180]
I want to run single test case by running 
`python setup.py test` 
but failed.

## Expected Result

Can see result of single test case  

## Actual Result

```
running test
running egg_info
writing requests.egg-info/PKG-INFO
writing dependency_links to requests.egg-info/dependency_links.txt
writing requirements to requests.egg-info/requires.txt
writing top-level names to requests.egg-info/top_level.txt
reading manifest file 'requests.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'NOTICE'
warning: no files found matching 'requirements.txt'
writing manifest file 'requests.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 111, in <module>
    'Source': 'https://github.com/kennethreitz/requests',
  File "/Users/magus0219/Documents/PycharmProjects/requests/venv/lib/python3.7/site-packages/setuptools-40.8.0-py3.7.egg/setuptools/__init__.py", line 145, in setup
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/magus0219/Documents/PycharmProjects/requests/venv/lib/python3.7/site-packages/setuptools-40.8.0-py3.7.egg/setuptools/command/test.py", line 228, in run
  File "setup.py", line 33, in run_tests
    errno = pytest.main(self.pytest_args)
  File "/Users/magus0219/Documents/PycharmProjects/requests/venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 58, in main
    config = _prepareconfig(args, plugins)
  File "/Users/magus0219/Documents/PycharmProjects/requests/venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 192, in _prepareconfig
    raise TypeError(msg.format(args, type(args)))
TypeError: `args` parameter expected to be a list or tuple of strings, got: 'tests/test_requests.py::TestRequests::test_invalid_url' (type: <class 'str'>)
```

## Reproduction Steps

```sh
./venv/bin/python3 setup.py test -a tests/test_requests.py::TestRequests::test_invalid_url

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.4"
  },
  "platform": {
    "release": "18.7.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "1000213f"
  },
  "urllib3": {
    "version": "1.25.3"
  },
  "using_pyopenssl": false
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment]
This was removed from Requests some time ago. It looks like we missed closing this.
