### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED -> During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by mattismyname** [psf/requests#5191]
Not sure if you'd consider this a bug, but from user's standpoint it's annoying because it causes messages printed to console that we'd rather not have printed. When SSL cert verification fails, there are several levels of unhandled exceptions being thrown from inside other exception handler contexts, which results in messages like this printed to the console:

Traceback (most recent call last):
  File "site-packages-link4/urllib3/connectionpool.py", line 594, in urlopen
  File "site-packages-link4/urllib3/connectionpool.py", line 810, in _prepare_proxy
  File "site-packages-link4/urllib3/connection.py", line 326, in connect
  File "site-packages-link4/urllib3/util/ssl_.py", line 325, in ssl_wrap_socket
  File "ssl.py", line 401, in wrap_socket
  File "ssl.py", line 808, in __init__
  File "ssl.py", line 1061, in do_handshake
  File "ssl.py", line 683, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages-link4/requests/adapters.py", line 440, in send
  File "site-packages-link4/urllib3/connectionpool.py", line 630, in urlopen
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "addr.py", line 122, in _MakeRPCCall
  File "site-packages-link4/requests/sessions.py", line 502, in request
  File "site-packages-link4/requests/sessions.py", line 634, in send
  File "site-packages-link4/requests/sessions.py", line 634, in <listcomp>
  File "site-packages-link4/requests/sessions.py", line 212, in resolve_redirects
  File "site-packages-link4/requests/sessions.py", line 612, in send
  File "site-packages-link4/requests/adapters.py", line 514, in send
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

## Expected Result
I expected request() to throw a single exception to me indicating the SSL failure, but not print all of the above messages to the console.

## Actual Result
See above

## Reproduction Steps

Use requests to reqeust a resource from a server where SSL verification will fail.

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.1"
  },
  "platform": {
    "release": "3.0.101-108.87-default",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.1"
  },
  "system_ssl": {
    "version": "1010103f"
  },
  "urllib3": {
    "version": "1.21.1"
  },
  "using_pyopenssl": false
}

```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sethmlarson** [comment]
This is a side-effect or urlli3b retries, Requests can't do anything about this unfortunately. Closing this issue.
