### ISSUE TITLE
URL in readme (https://2.python-requests.org/) is http only

### ISSUE THREAD

**Issue by chmreid** [psf/requests#5212]
The URL `//2.python-requests.org/` (which is in the readme) automatically resolves to `https://2.python-requests.org` which is down (there is no HTTPS version of the site). The HTTP version of the site, `http://2.python-requests.org`, is fine.

## Expected Result

I expect that when I click the link in the readme, it goes to a page that exists.

## Actual Result

When I click the link in the readme, the `//` prefix resolves to `https://`, but there is no HTTPS version of `2.python-requests.org`, so the page does not load.

## Reproduction Steps

```
>>> import requests

>>> requests.get('https://2.python-requests.org/')
Traceback (most recent call last):
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 472, in wrap_socket
    cnx.do_handshake()
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1716, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1456, in _raise_ssl_error
    _raise_current_error()
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert internal error')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 478, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert internal error')],)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='2.python-requests.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert internal error')],)",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/charles/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='2.python-requests.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert internal error')],)",),))

>>> requests.get('http://2.python-requests.org/')
<Response [200]>
```

## System Information

N/A

**Comment by kennethreitz** [comment]
I moved the site to requests.kennethreitz.org, in preparation to it being requests.psf.org (or something similar, ideally).

**Comment by ashb** [comment]
Can you fix up the redirect from `docs.pyhon-requests.org' so that it doesn't redirect to a URL that cannot work? 

`http://docs.python-requests.org/en/master/objects.inv` -> `https://2.python-requests.org//en/master/objects.inv` which now doesn't work.

It would be nice if the all old URLs could continue working and 30X to the new location.

**Comment by aboncok** [comment]
requests.kennethreitz.org is blocked by company policy. docs.pyhon-requests.org was working fine.

**Comment by charlesreid1** [comment]
bump

**Comment by ssbarnea** [comment]
Is anyone working to fix this? Mainly I am forced to remove requests documentation links due to this bug.

**Comment by pelid** [comment]
Link to the documention on PyPi page is not working.

![image](https://user-images.githubusercontent.com/870324/66848688-34aa3b00-ef7e-11e9-9d66-a0ce48510d80.png)

[https://pypi.org/project/requests2/](https://pypi.org/project/requests2/)

**Comment by jtrakk** [comment]
https://requests.readthedocs.io/ is working fine as far as I can tell.

**Comment by chmreid** [comment]
URL in readme was changed by @Leetcore

https://github.com/psf/requests/commit/74b72ce4265583db0430080ab67d3d5e0c4b44b2

Closing this issue, as 2.python-requests.org is no longer mentioned anywhere in docs

**Comment by ashb** [comment]
Search results still use this URL - search for `get` and then choose the first result - the URL is https://2.python-requests.org/en/master/user/install/#get-the-source-code

**Comment by ashb** [comment]
And as @pelid mentioned the published release still links to http://docs.python-requests.org/ which redirects to https://2.python-requests.org/ which doesn't work.

**Comment by ssbarnea** [comment]
Just made an attempt to fix the docs. The amount of links inside the documentation would make a SEO Marketer envious. I doubt that's possible to repeat yourself more often that with this.

Please have a look and point if there are mistakes.

**Comment by chmreid** [comment]
> The amount of links inside the documentation would make a SEO Marketer envious.

Sounds like a great application for Jinja2 ;)

**Comment by chmreid** [comment]
Re-opening until @ssbarnea's pull request #5236 is merged, since there are a lot more links than I initially thought when I closed this issue
