### ISSUE TITLE
zlib.error: Error -3 while decompressing data: invalid distance too far back

### ISSUE THREAD

**Issue by zablah** [psf/requests#5213]
## Expected Result

I installed requests on raspberry pi and every thing run good but suddenly I can't start requests module and I got the following error

## Reproduction Steps

```python
import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/requests/packages/__init__.py", line 59, in <module>
    vendored('urllib3.contrib.pyopenssl')
  File "/usr/lib/python2.7/dist-packages/requests/packages/__init__.py", line 32, in vendored
    __import__(vendored_name, globals(), locals(), level=0)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 13, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, rsa
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 14, in <module>
    from cryptography.hazmat.backends.interfaces import RSABackend
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
zlib.error: Error -3 while decompressing data: invalid distance too far back


```

## System Information
```
    $ python -m requests.help

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/requests/packages/__init__.py", line 59, in <module>
    vendored('urllib3.contrib.pyopenssl')
  File "/usr/lib/python2.7/dist-packages/requests/packages/__init__.py", line 32, in vendored
    __import__(vendored_name, globals(), locals(), level=0)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 13, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, rsa
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 14, in <module>
    from cryptography.hazmat.backends.interfaces import RSABackend
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
zlib.error: Error -3 while decompressing data: invalid distance too far back

```
my python version is python 2.7.13

**Comment by sethmlarson** [comment]
`python -m pip freeze` might be useful to debug this issue. It looks like a file is getting decompressed in a way that doesn't work on a 32 bit machine perhaps?

**Comment by zablah** [comment]
I solve this issue by upgrade  setuptools
```
pip install --upgrade setuptools
```
