### ISSUE TITLE
HTTPS under Jython 2.7.2 failes

### ISSUE THREAD

**Issue by lukicsl** [psf/requests#5423]
I am not able to use request for https site, without SSL things run fine
Jython 2.7.2 running in a docker container.
```
root@5ddd8c24f29b:/# python
Jython 2.7.2 (v2.7.2:925a3cc3b49d, Mar 21 2020, 10:03:58)
[OpenJDK Server VM (AdoptOpenJDK)] on java14
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> import json
>>> r =requests.get('http://api.eiswarnung.de/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/jython/Lib/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/jython/Lib/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/jython/Lib/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/jython/Lib/site-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/jython/Lib/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/usr/local/jython/Lib/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/jython/Lib/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.eiswarnung.de', port=443): Max retries exceeded with url: /api/public/ (Caused by SSLError(SSLError(1, u'Received fatal alert: internal_error'),))
>>> 

```

**Comment by sigmavirus24** [comment]
This is unsurprising since Jython isn't part of the CI for this project and no one tests it.

**Comment by lukicsl** [comment]
> This is unsurprising since Jython isn't part of the CI for this project and no one tests it.

Does this mean that actually nobody will followup with anything as a suggestion/solution?
I am not that experienced in python development.

**Comment by sigmavirus24** [comment]
> Does this mean that actually nobody will followup with anything as a suggestion/solution?

I don't think anyone involved with the project uses Jython or tests against it. Beyond that, this doesn't seem to be a problem with Requests but more likely a problem with that specific website and Jython based upon the exception message `Received fatal alert: internal_error` and https://github.com/jythontools/jython/issues/165

**Comment by lukicsl** [comment]
Opened a ticket at jython

**Comment by lukicsl** [comment]
the same happens with urllib3:
```
root@34b4e3a1e41b:/# python
Jython 2.7.2 (v2.7.2:925a3cc3b49d, Mar 21 2020, 10:03:58)
[OpenJDK Server VM (AdoptOpenJDK)] on java14
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib3
>>> http = urllib3.PoolManager()
>>> r = http.request('GET', 'http://api.eiswarnung.de/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/jython/Lib/site-packages/urllib3/request.py", line 75, in request
    return self.request_encode_url(
  File "/usr/local/jython/Lib/site-packages/urllib3/request.py", line 97, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/jython/Lib/site-packages/urllib3/poolmanager.py", line 369, in urlopen
    return self.urlopen(method, redirect_location, **kw)
  File "/usr/local/jython/Lib/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/jython/Lib/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/local/jython/Lib/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/local/jython/Lib/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/local/jython/Lib/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.eiswarnung.de', port=443): Max retries exceeded with url: /api/public/ (Caused by SSLError(SSLError(1, u'Received fatal alert: internal_error'),))
>>> 
```
