### ISSUE TITLE
407 Proxy Requires Authentication

### ISSUE THREAD

**Issue by scullcandyz** [psf/requests#5545]
I cant seem to send any requests with auth proxies, I know for a fact the way I have it set up should theoretically work. Proxies are being passed in the correct format, I tried passing them to requests in all possible ways. 

I tried: 
- Reinstall Requests
- Pass requests the proxies in all possible ways
- Create completely fresh venv with just requests
- 3 different proxy providers (which I know all work)
- sess.trust_env=False

-Python 3.7
-Windows
-requests 2.24
-urllib3 1.25.10

I dont remember doing any changes to my venv that should matter, but it has to be something along that way as everything worked just fine yesterday. Maybe im missing something you can spot out right away, thanks in advance been sitting here for 5 hours now reading through everything I can find but cant seem to fix it up.

Edit: Im completely lost now, im getting the same issue when running in python console on a different python version (3.8)

Code (tried passing in as arg in s.get, tried passing in auth and proxy´s seperately):
```
s = requests.session()
proxy = {'http': 'user:pass@ip:port', 'https': 'user:pass@ip:port'}
s.proxies = proxy
s.get("https://www.google.com")
```

Full traceback:

```Traceback (most recent call last):
  File "C:\Users\\PycharmProjects\test123\venv\lib\site-packages\urllib3\connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\\PycharmProjects\test123\venv\lib\site-packages\urllib3\connectionpool.py", line 805, in _prepare_proxy
    conn.connect()
  File "C:\Users\\PycharmProjects\test123\venv\lib\site-packages\urllib3\connection.py", line 308, in connect
    self._tunnel()
  File "C:\Users\\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 923, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 407 Proxy Authentication Required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\\PycharmProjects\test123\venv\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\\PycharmProjects\test123\venv\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\\PycharmProjects\test123\venv\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.google.de', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users//PycharmProjects/test123/testr.py", line 6, in <module>
    r.get("https://www.google.de")
  File "C:\Users\\PycharmProjects\test123\venv\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\\PycharmProjects\test123\venv\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\\PycharmProjects\test123\venv\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\\PycharmProjects\test123\venv\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.google.de', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))```

**Comment by nametkin** [comment]
Either your proxy server requires authentication different from the basic one, or you did not enter the username and password correctly in the proxy_url. To begin with, you can send a request to your proxy server and look at the header 'Proxy-Authenticate' of response. It will indicate the type of authentication that the proxy requires. For example, you can do it like this:

```
proxy_resp = requests.get('your_proxy_url')
print(proxy_resp.headers['Proxy-Authenticate'])
```
The path to solving your problem will depend on what this `print `outputs.

**Comment by scullcandyz** [comment]
Hey thanks for your answer, the issue resolved itself. I have no clue why or how. But it did over night, changed nothing same proxies lol  can be closed
