### ISSUE TITLE
nested dict with multipart/form-data

### ISSUE THREAD

**Issue by Poolitzer** [psf/requests#5565]
Hello there.

I am trying to send a post request with a nested dict which contains files, but it fails at urrlib3 level.

This is a minimal working example dict

`{"media": [{"type": "photo", "media": open("besttest.jpg", "rb")}, {"type": "video", "media": open("bettertest.mp4", "rb"),"thumb": open("index.jpeg", "rb")}]}`

And I am doing the request like this:

`requests.post("URL", files=dict)`

This now results in the following error:

```
Traceback (most recent call last):
  File "C:/Users/Poolitzer/AppData/Roaming/JetBrains/PyCharm2020.1/scratches/scratch.py", line 5, in <module>
    response = requests.post("URL",
  File "C:\Users\Poolitzer\PycharmProjects\test\venv\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Poolitzer\PycharmProjects\test\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Poolitzer\PycharmProjects\test\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "C:\Users\Poolitzer\PycharmProjects\test\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "C:\Users\Poolitzer\PycharmProjects\test\venv\lib\site-packages\requests\models.py", line 317, in prepare
    self.prepare_body(data, files, json)
  File "C:\Users\Poolitzer\PycharmProjects\test\venv\lib\site-packages\requests\models.py", line 505, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "C:\Users\Poolitzer\PycharmProjects\test\venv\lib\site-packages\requests\models.py", line 166, in _encode_files
    rf.make_multipart(content_type=ft)
  File "C:\Users\Poolitzer\PycharmProjects\test\venv\lib\site-packages\urllib3\fields.py", line 267, in make_multipart
    self._render_parts(
  File "C:\Users\Poolitzer\PycharmProjects\test\venv\lib\site-packages\urllib3\fields.py", line 225, in _render_parts
    parts.append(self._render_part(name, value))
  File "C:\Users\Poolitzer\PycharmProjects\test\venv\lib\site-packages\urllib3\fields.py", line 205, in _render_part
    return self.header_formatter(name, value)
  File "C:\Users\Poolitzer\PycharmProjects\test\venv\lib\site-packages\urllib3\fields.py", line 116, in format_header_param_html5
    value = _replace_multiple(value, _HTML5_REPLACEMENTS)
  File "C:\Users\Poolitzer\PycharmProjects\test\venv\lib\site-packages\urllib3\fields.py", line 89, in _replace_multiple
    result = pattern.sub(replacer, value)
TypeError: expected string or bytes-like object
```

**Comment by sigmavirus24** [comment]
There's no documentation that shows this would work so it's unclear to me why you think this is a bug. If you want help making this work, please use StackOverflow. This is a defect tracker, not a Q&A website

**Comment by Poolitzer** [comment]
I just expected it to work, why is it limited? And there was a question template, so I assumed issues can just be questions as well, sorry.

**Comment by sigmavirus24** [comment]
The [question template](https://github.com/psf/requests/blob/48237afd9d064c639b9c2bcea7e75ab7b717b181/.github/ISSUE_TEMPLATE/Custom.md) tells you to go to StackOverflow.

**Comment by nateprewitt** [comment]
Resolving since this isn't intended functionality for the `files` param. This functionality should be fairly simple to implement in whatever code is using Requests.
