### ISSUE TITLE
Bad SSL Handshake on Windows 10

### ISSUE THREAD

**Issue by modbender** [psf/requests#5576]
When I do `requests.get(self.feed_url)`

```
Traceback (most recent call last):
  File "C:\Users\UserName\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\UserName\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\UserName\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "C:\Users\UserName\AppData\Roaming\Python\Python38\site-packages\urllib3\connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(

  File "C:\Users\UserName\AppData\Roaming\Python\Python38\site-packages\urllib3\util\ssl_.py", line 384, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "feed.py", line 47, in get_feed
    req = requests.get(self.feed_url)
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))
```

And when I do `requests.get(self.feed_url, verify=False)`

I have been getting this traceback when doing requests
```
Traceback (most recent call last):
  File "C:\Users\UserName\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\UserName\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\UserName\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "C:\Users\UserName\AppData\Roaming\Python\Python38\site-packages\urllib3\connection.py", line 362, in connect

    self.sock = ssl_wrap_socket(
  File "C:\Users\UserName\AppData\Roaming\Python\Python38\site-packages\urllib3\util\ssl_.py", line 384, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\UserName\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(

  File "C:\Users\UserName\AppData\Roaming\Python\Python38\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\UserName\AppData\Roaming\Python\Python38\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\UserName\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
    req = requests.get(self.feed_url, verify=False)
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\UserName\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

The URL is fine, because I was using the same URL just 2 days back and have not edited the files and it was fine. 

I also tried installing certificate from https://www.securly.com/ssl and Installed openssl and added bin folder of openssl to PATH and restarted pc, still not working.

**EDIT:** OK, I tested it with other urls and looks like it's that website specific, here is the URL that I was trying to get: [URL](https://horriblesubs.info/shows/yahari-ore-no-seishun-love-come-wa-machigatteiru-kan/)
Any help accepted.

On Windows 10 with requests 2.24.0

**Comment by modbender** [comment]
Closing this as it is similar to #3774

**Comment by modbender** [comment]
After a lot of tests, it turns that the website was blocked by ISP, I was using 1.1.1.1 DNS to bypass it on browser, but didn't work for python.
