### ISSUE TITLE
Cannot pass in client certs while using a session

### ISSUE THREAD

**Issue by jsmaupin** [psf/requests#5685]
I get contradicting exceptions when I try to pass in a client certificate and private key into a session object that is used for the request.

## Expected Result

Using a client cert and private key will work with sessions just as it does with a request that is not in a session.

## Actual Result

If I use:
```python
self.session.cert = client_cert
```

I get back an error statement that stated that it tried to use the client_cert as a tuple, but it is not a tuple. I also changed this single file to contain both the client cert and the private key, where the private key was pasted below the client cert and I receive the same error.

```
Traceback (most recent call last):
  File "/home/jmaupin/dev/pymeasure/pymeasure/client.py", line 245, in _upload
    response = self.session.send(prepped,
  File "/home/jmaupin/dev/sandbox/venv/lib64/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/jmaupin/dev/sandbox/venv/lib64/python3.8/site-packages/requests/adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/home/jmaupin/dev/sandbox/venv/lib64/python3.8/site-packages/requests/adapters.py", line 244, in cert_verify
    conn.key_file = cert[1]
IndexError: tuple index out of range
```

If I change the cert parameter on the session object to be a tuple, I get a result stating that it cannot be a tuple. 

```python
self.session.cert = client_cert, client_key
```

Or,

```python
self.session.cert = (client_cert, client_key)
```
```
Traceback (most recent call last):
  File "/home/jmaupin/dev/pymeasure/pymeasure/client.py", line 245, in _upload
    response = self.session.send(prepped,
  File "/home/jmaupin/dev/sandbox/venv/lib64/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/jmaupin/dev/sandbox/venv/lib64/python3.8/site-packages/requests/adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/home/jmaupin/dev/sandbox/venv/lib64/python3.8/site-packages/requests/adapters.py", line 248, in cert_verify
    if conn.cert_file and not os.path.exists(conn.cert_file):
  File "/usr/lib64/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not tuple
```

## Reproduction Steps

```python
import requests
session = Session()
self.session.cert = client_cert, client_key
request = Request('POST', url, data=payload)
prepped = self.session.prepare_request(request)
response = self.session.send(prepped)
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.9"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.8.6"
  },
  "platform": {
    "release": "5.9.11-100.fc32.x86_64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.25.0"
  },
  "system_ssl": {
    "version": "1010107f"
  },
  "urllib3": {
    "version": "1.25.11"
  },
  "using_pyopenssl": false
}

```

**Comment by jsmaupin** [comment]
I resolved this. I had a stray comma in my code.
