### ISSUE TITLE
Cookies are lost on 307 redirects

### ISSUE THREAD

**Issue by gil9red** [psf/requests#5709]
When I submit a request, I get a 307 response and a cookie. But when the request is repeated, the cookie is not added.

Added request logging:
```
try:
    import http.client as http_client
except ImportError:
    # Python 2
    import httplib as http_client
http_client.HTTPConnection.debuglevel = 1

# You must initialize logging, otherwise you'll not see debug output.
import logging
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True
```

Result (first 2 requests):
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.dns-shop.ru:443
send: b'GET /product/4d664a0d90d61b80/processor-amd-ryzen-7-3700x-oem/ HTTP/1.1\r\nHost: www.dns-shop.ru\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
DEBUG:urllib3.connectionpool:https://www.dns-shop.ru:443 "GET /product/4d664a0d90d61b80/processor-amd-ryzen-7-3700x-oem/ HTTP/1.1" 307 0
reply: 'HTTP/1.1 307 TemporaryRedirect\r\n'
header: Server: Variti/0.9.3a
header: Date: Fry, 25 Dec 2020 14:3753 GMT
header: Set-Cookie: ipp_uid_tst=1608907073940/2LhuRHu-NT--na0AX4hLKg; Expires=; Domain=; Path=/
header: Location: /product/4d664a0d90d61b80/processor-amd-ryzen-7-3700x-oem/
header: Connection: keep-alive
header: Keep-Alive: timeout=60
header: Content-Length: 0

send: b'GET /product/4d664a0d90d61b80/processor-amd-ryzen-7-3700x-oem/ HTTP/1.1\r\nHost: www.dns-shop.ru\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\n\r\n'
DEBUG:urllib3.connectionpool:https://www.dns-shop.ru:443 "GET /product/4d664a0d90d61b80/processor-amd-ryzen-7-3700x-oem/ HTTP/1.1" 307 0
reply: 'HTTP/1.1 307 TemporaryRedirect\r\n'
header: Server: Variti/0.9.3a
header: Date: Fry, 25 Dec 2020 14:3754 GMT
header: Set-Cookie: ipp_uid_tst=1608907074028/oOg1XsGU12ZE8PkUludY5g; Expires=; Domain=; Path=/
header: Location: /product/4d664a0d90d61b80/processor-amd-ryzen-7-3700x-oem/
header: Connection: keep-alive
header: Keep-Alive: timeout=60
header: Content-Length: 0
```

## Expected Result

HTTP 200, OK

## Actual Result

```
Traceback (most recent call last):
  File "C:/Users/ipetrash/Projects/SimplePyScripts/html_parsing/www_dns_shop_ru/get_price.py", line 17, in <module>
    rs = requests.get('https://www.dns-shop.ru/')
  File "C:\Users\ipetrash\Anaconda3\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\ipetrash\Anaconda3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\ipetrash\Anaconda3\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ipetrash\Anaconda3\lib\site-packages\requests\sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "C:\Users\ipetrash\Anaconda3\lib\site-packages\requests\sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Users\ipetrash\Anaconda3\lib\site-packages\requests\sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

## Reproduction Steps

```python
import requests

session = requests.session()
rs = session.get('https://www.dns-shop.ru/')
print(rs)
```

## System Information

    $ python -m requests.help

```
{                                   
  "chardet": {                      
    "version": "3.0.4"              
  },                                
  "cryptography": {                 
    "version": "2.7"                
  },                                
  "idna": {                         
    "version": "2.8"                
  },                                
  "implementation": {               
    "name": "CPython",              
    "version": "3.7.3"              
  },                                
  "platform": {                     
    "release": "10",                
    "system": "Windows"             
  },                                
  "pyOpenSSL": {                    
    "openssl_version": "1010103f",  
    "version": "17.2.0"             
  },                                
  "requests": {                     
    "version": "2.25.1"             
  },                                
  "system_ssl": {                   
    "version": "1010108f"           
  },                                
  "urllib3": {                      
    "version": "1.24.2"             
  },                                
  "using_pyopenssl": true           
}                                   
```

**Comment by gil9red** [comment]
Rewrote the code to manually handle redirects and forwarding cookies.

PS. after I sent the cookie, there was no 307 on subsequent requests.

They have interesting protection ...

[Code:](https://github.com/gil9red/SimplePyScripts/blob/7c3fc621399d7ec32bfde9174d5d47dfed30282d/html_parsing/www_dns_shop_ru/get_price.py#L31)
```
from http.cookies import SimpleCookie
from typing import Optional
from urllib.parse import urljoin

import requests

session = requests.session()
session.headers['User-Agent'] = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0'

def get_price(url: str) -> Optional[int]:
    cookies = None
    attempts = 30

    while True:
        attempts -= 1
        if attempts <= 0:
            raise Exception('Too many redirects!')

        rs = session.get(url, allow_redirects=False, cookies=cookies)

        redirect_url = rs.headers.get('Location')
        if redirect_url:
            url = urljoin(rs.url, redirect_url)
            if rs.cookies:
                cookies = rs.cookies
                continue

            cookies = rs.headers.get('Set-Cookie')
            if cookies:
                cookies = {key: value.value for key, value in SimpleCookie(cookies).items()}

            continue

        break
    ...
```
