### ISSUE TITLE
Requests don't work within a celery async task

### ISSUE THREAD

**Issue by augustosamame** [psf/requests#5786]
When running this in Django shell:

```
import requests
response = requests.get('https://auth.myfanpark.com/health')
```

I get a valid response

The same 2 lines when ran as async celery job in the same Django project:

```
import requests
response = requests.get('https://auth.myfanpark.com/health')
```

Exception: too many values to unpack (expected 2)

## Expected Result

For requests call to work correctly in async celery calls just like in regular Django shell.

## Actual Result

Exception: too many values to unpack (expected 2)

## Reproduction Steps

```python
import requests
response = requests.get(url = 'https://auth.myfanpark.com/health')

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.7"
  },
  "platform": {
    "release": "19.6.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.21.0"
  },
  "system_ssl": {
    "version": "1010109f"
  },
  "urllib3": {
    "version": "1.24.1"
  },
  "using_pyopenssl": false
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sethmlarson** [comment]
Can we get the full traceback? One line of the traceback isn't useful for figuring out the issue here.

**Comment by sigmavirus24** [comment]
Also, I use requests in Celery and it works fine. So I'm pretty close to closing this.

**Comment by augustosamame** [comment]
I will have a stack trace soon.

**Comment by augustosamame** [comment]
This is the complete stack trace:

```
Apr 5 15:55:01 production-celery-ec2 worker.log ERROR Task cancel_notification_no_response[053c87fc-ed50-477a-a757-73c35a00c85f] raised unexpected: ValueError('too many values to unpack (expected 2)',)
Apr 5 15:55:01 production-celery-ec2 worker.log Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/releases/eb0a086fdd0165da73a3fdea33d0be78a0523ce4/stargramz/tasks.py", line 186, in cancel_starsona_celebrity_no_response
    dummy_response = requests.get('https://auth.myfanpark.com/health')
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/db/models/query.py", line 399, in get
    clone = self.filter(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1187, in build_filter
    arg, value = filter_expr
Apr 5 15:55:01 production-celery-ec2 worker.log ValueError: too many values to unpack (expected 2)
```

**Comment by sigmavirus24** [comment]
Reading your stack trace the important bits are:

```
File "/home/ubuntu/releases/eb0a086fdd0165da73a3fdea33d0be78a0523ce4/stargramz/tasks.py", line 186, in cancel_starsona_celebrity_no_response
dummy_response = requests.get('https://auth.myfanpark.com/health')
File "/home/ubuntu/.local/lib/python3.6/site-packages/django/db/models/query.py", line 399, in get
clone = self.filter(*args, **kwargs)
File "/home/ubuntu/.local/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
return self._filter_or_exclude(False, *args, **kwargs)
File "/home/ubuntu/.local/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
clone.query.add_q(Q(*args, **kwargs))
File "/home/ubuntu/.local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
clause, _ = self._add_q(q_object, self.used_aliases)
File "/home/ubuntu/.local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
split_subq=split_subq, simple_col=simple_col,
File "/home/ubuntu/.local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1187, in build_filter
arg, value = filter_expr
Apr 5 15:55:01 production-celery-ec2 worker.log ValueError: too many values to unpack (expected 2)
```

Which indicates that `requests` is a Django ORM manager and not the requests library.
