### ISSUE TITLE
SOCKS5 Timeout

### ISSUE THREAD

**Issue by CollabSensei** [psf/requests#5787]
Summary.

## Expected Result

Successful HTTP post via SOCKS5 Proxy. The web service takes about 2-3 minutes to respond. When connecting directly, without SOCKS5, it works fine. Using a Dante Socks5 proxy. Dante logs indicate that the client closed the connection.

## Actual Result

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

## Reproduction Steps

```python
url = "https://" + hostname + ":" + api_port + "/axl/"
bodyUpdate = """
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/%version">
<soapenv:Header/>
<soapenv:Body>
    <ns:doSmartLicenseRegister>
        <token>%token</token>
        <force>true</force>
    </ns:doSmartLicenseRegister>
</soapenv:Body>
</soapenv:Envelope>"""

bodyUpdate = bodyUpdate.replace("%version",str(version))
bodyUpdate = bodyUpdate.replace("%token", getSmartLicenseToken('myToken')) 

sock5Proxy = {
    'http': 'socks5h://' + vapp_ip + ':1080',
    'https':'socks5h://' + vapp_ip + ':1080'
}

response = requests.post(url, data=bodyUpdate, auth=(username,password), headers={'SOAPAction': 'CUCM:DB ver=14.0'}, proxies=sock5Proxy, verify = False)



```

## System Information

{
  "chardet": {
    "version": "4.0.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.6"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.25.1"
  },
  "system_ssl": {
    "version": "100020ff"
  },
  "urllib3": {
    "version": "1.26.3"
  },
  "using_pyopenssl": false

```
<paste here>
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment]
We rely on urllib3 for socks proxying and you've already opened https://github.com/urllib3/urllib3/issues/2195 so I'm closing this
