### ISSUE TITLE
SSL requests error in version 2.25.1 (upgraded from version 2.24.0)

### ISSUE THREAD

**Issue by M-Stenzel** [psf/requests#5788]
Dear team,

I am using requests for the searx search engine (https://github.com/searx/searx)

The script below throws this error and I do not know whether this is related to python-requests or to searx or my specific installation?

System is opensuse, python 3.6.12. latest requests release (2.25.1).

This (original searx) code gives me the error

#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'searx==1.0.0','console_scripts','searx-run'
__requires__ = 'searx==1.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('searx==1.0.0', 'console_scripts', 'searx-run')()
    )

Output with error message:
Serving Flask app "searx.webapp" (lazy loading)
Environment: production
WARNING: This is a development server. Do not use it in a production deployment.
Use a production WSGI server instead.
Debug mode: off
INFO:werkzeug: * Running on http://127.0.0.1:8898/ (Press CTRL+C to quit)
ERROR:searx.engines:yggtorrent engine: Fail to initialize
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
chunked=chunked,
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
self._validate_conn(conn)
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in validate_conn
conn.connect()
File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 360, in connect
ssl_context=context,
File "/usr/lib/python3.6/site-packages/urllib3/util/ssl.py", line 370, in ssl_wrap_socket
return context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/lib64/python3.6/ssl.py", line 407, in wrap_socket
_context=self, _session=session)
File "/usr/lib64/python3.6/ssl.py", line 817, in init
self.do_handshake()
File "/usr/lib64/python3.6/ssl.py", line 1077, in do_handshake
self._sslobj.do_handshake()
File "/usr/lib64/python3.6/ssl.py", line 689, in do_handshake
self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
timeout=timeout
File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www4.yggtorrent.li', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

Obviously there seem to be problems with SSL/certificate.

Martin.

P. S. This is kinda of crosspost (I know, maybe not the best idea...)
The other post to be found here: 

https://github.com/searx/searx/issues/2731

**Comment by sigmavirus24** [comment]
Did you downgrade to the prior working version of requests? If not. Please try that. I doubt you'll see a difference here.
