### ISSUE TITLE
Working proxies throwing error in requests

### ISSUE THREAD

**Issue by analogaio** [psf/requests#5999]
I gave my friends my exact code with the same proxy, it works for 4 different people, but fails for me and another. 

## Expected Result

For the request to give a valid response / not fail

## Actual Result

Traceback (most recent call last):
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 371, in connect
    self._tunnel()
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 922, in _tunnel
    (version, code, message) = response._read_status()
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 279, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Allen/Desktop/AnalogAIO CLI/ProxyTest.py", line 15, in <module>
    res = session.get("https://httpbin.org/")
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Allen\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

## Reproduction Steps

```python
import requests

session = requests.Session()
proxy = "ip:port:user:pass"  # Put an actual proxy here

# split proxy into host and port and user and password
host, port, user, password = proxy.split(":")

proxies = {
    "http": "http://{}:{}@{}:{}".format(user, password, host, port),
    "https": "http://{}:{}@{}:{}".format(user, password, host, port)
}

session.proxies.update(proxies)
response = session.get("https://httpbin.org/")
print(response.status_code)

```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": "3.0.4"
  },
  "charset_normalizer": {
    "version": "2.0.9"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.9"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.26.0"
  },
  "system_ssl": {
    "version": "1010107f"
  },
  "urllib3": {
    "version": "1.26.7"
  },
  "using_charset_normalizer": false,
  "using_pyopenssl": false
}
```

Running on Python 3.7.9 and Windows 11.

**Comment by JimmyJay2015** [comment]
您好，您的邮件我已收到，我会尽快给您回复。

**Comment by sigmavirus24** [comment]
> ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

Indicates that your proxy isn't accepting connections from you or your other friend. That's a networking issue between you and the proxy.

In the future, please use StackOverflow for questions and technical support like this
