### ISSUE TITLE
Unicode surrogates in POST data lead to exception

### ISSUE THREAD

**Issue by pcworld** [psf/requests#6008]
In requests 2.26.0 with Python 3, when passing unicode strings with surrogate characters as POST data (either directly as a `str` or as part of a `dict`), sending the request crashes.

## Expected Result

The library should not crash, even when fed with unvalidated user input.

## Actual Result / Reproduction Steps

```
>>> import requests
>>> requests.__version__
'2.26.0'

>>> requests.post('https://example.invalid', data={'name': 'test\udced\udcb3\udc83.pdf'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.7/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/user/.local/lib/python3.7/site-packages/requests/sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/user/.local/lib/python3.7/site-packages/requests/models.py", line 319, in prepare
    self.prepare_body(data, files, json)
  File "/home/user/.local/lib/python3.7/site-packages/requests/models.py", line 515, in prepare_body
    body = self._encode_params(data)
  File "/home/user/.local/lib/python3.7/site-packages/requests/models.py", line 104, in _encode_params
    v.encode('utf-8') if isinstance(v, str) else v))
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 4-6: surrogates not allowed

>>> requests.post('https://example.com/', 'test\udced\udcb3\udc83.pdf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    body = _encode(body, 'body')
  File "/usr/lib/python3.8/http/client.py", line 164, in _encode
    raise UnicodeEncodeError(
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 4-6: Body ('\udced\udcb3\udc83') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": "3.0.4"
  }, 
  "cryptography": {
    "version": ""
  }, 
  "idna": {
    "version": "2.10"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.16"
  }, 
  "platform": {
    "release": "4.19.0-17-amd64", 
    "system": "Linux"
  }, 
  "pyOpenSSL": {
    "openssl_version": "", 
    "version": null
  }, 
  "requests": {
    "version": "2.24.0"
  }, 
  "system_ssl": {
    "version": "1010104f"
  }, 
  "urllib3": {
    "version": "1.25.11"
  }, 
  "using_pyopenssl": false
}
```
-----
In [requests/models.py](https://github.com/psf/requests/blob/main/requests/models.py), there are several calls like `some_string.encode('utf-8')`. I suppose changing them to `some_string.encode('utf-8', 'surrogatepass')` would at least fix the first reproduction case. Not sure about the second, since the exception occurs in http.client there.

**Comment by mathewOracle** [comment]
HI @nateprewitt, @sigmavirus24 

This still reproduces on 2.32.4:

```python
>>> import requests
>>> requests.post('https://example.invalid', data={'name': 'test\udced\udcb3\udc83.pdf'})
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 4-6: surrogates not allowed
```

It comes from '_encode_params' in 'models.p',, where each value is encoded with 'v.encode("utf-8")'.

I don't think requests can reasonably make this call succeed -- unpaired surrogates genuinely can't be represented in UTF-8, and re-encoding with 'errors="surrogateescape"' would silently put mangled bytes on the wire and hide what is usually a decoding bug in the caller's own code. What does seem worth improving is the error itself: right now it reports a byte offset into an intermediate value and gives no hint which field caused it, which is awkward on a request with many fields.

I have a change that keeps the behaviour identical but makes the message name the offending field:
```
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 4-6:
surrogates not allowed; the value for field 'name' contains an unpaired UTF-16 surrogate that cannot be represented in UTF-8 -- check that the input was decoded correctly before passing it to requests
```

It re-raises the same **UnicodeEncodeError** type rather than introducing a new exception, so anything already catching **UnicodeEncodeError** around a request keeps working. Two files, +49/-2, with a regression test; 'ruff format' and 'ruff check' are clean and the existing tests pass.

The branch is here:
https://github.com/mathewOracle/requests/tree/fix/6008-surrogate-encode-error-message

I went to open a PR but the repo currently limits pull requests to collaborators, so I can't. Happy to open one whenever that changes, or to adjust the approach if you'd rather this were handled differently.
