### ISSUE TITLE
Throwing a UnicodeEncodeError

### ISSUE THREAD

**Issue by killabit** [psf/requests#6076]
Traceback (most recent call last):
  File "/usr/share/doc/hackingtool/hackingtool.py", line 109, in <module>
    all_tools.show_options()
  File "/usr/share/doc/hackingtool/core.py", line 161, in show_options
    self.show_info()
  File "/usr/share/doc/hackingtool/hackingtool.py", line 71, in show_info
    print(logo + '\033[0m \033[97m')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 9-10: ordinal not in range(256)

**Comment by nateprewitt** [comment]
Hi @killabit,

Nothing in this stacktrace is related to Requests. We won't be able to help here.
