### ISSUE TITLE
HTTPDigestAuth fails on non-latin credentials

### ISSUE THREAD

**Issue by ondratu** [psf/requests#6102]
There was issue reported, which is closed with bad results.

https://github.com/psf/requests/blob/4f6c0187150af09d085c03096504934eb91c7a9e/requests/auth.py#L59-L63

Don't pass unicode strings in the arguments, but use UTF8 bytes instead.
```
self.session.get(main_url, auth=requests.auth.HTTPDigestAuth("Сергей_Ласточкин".encode('UTF-8'), '1234'))
```

_Originally posted by @D-stefaang in https://github.com/psf/requests/issues/5089#issuecomment-763569911_

But this is wrong! When i try to set user 'Ondřej' with this advice, requests send bad string:

```
HTTPDigestAuth(user, 'heslíčko')
```
creates header starts with wrong username!
```
Digest username="b'Ond\xc5\x99ej'"
```

**Comment by nateprewitt** [comment]
Hi @ondratu,

Could you please clarify what you believe is wrong in this case? `ř` is the byte-sequence `\xc5\x99` in UTF-8, so we'd expect the bytes object to be `Ond\xc5\x99ej`. We can quickly verify this by checking:

```python
'Ondřej'.encode('utf-8') == b'Ond\xc5\x99ej'
>>> True
```

It's not clear what other value you'd be expecting.

**Comment by nateprewitt** [comment]
Hmm, on closer inspection this does appear to be a bug. We're using the bytes username as an argument to [format our string](https://github.com/psf/requests/blob/2d5517682b3b38547634d153cea43d48fbc8cdb5/requests/auth.py#L215-L225) for the header. This causes the full literal `"b'Ond\xc5\x99ej'"` to be used which I agree doesn't look correct. This header _should_ be encoded as bytes during creation but we currently defer that to be urllib3's problem.

When not encoding the auth/password, we get this:

```python
Traceback (most recent call last):
  File "/Users/nateprewitt/Work/OpenSource/requests/test.py", line 3, in <module>
    r = requests.get('https://httpbin.org/digest-auth/auth/Ondřej/heslíčko', auth=h)
  File "/Users/nateprewitt/Work/OpenSource/requests/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  [...]
  File "/Users/nateprewitt/.pyenv/versions/3.10.3/lib/python3.10/http/client.py", line 1323, in _send_request
    self.putheader(hdr, value)
  File "/Users/nateprewitt/.pyenv/versions/3.10.3/lib/python3.10/site-packages/urllib3/connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "/Users/nateprewitt/.pyenv/versions/3.10.3/lib/python3.10/http/client.py", line 1255, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0159' in position 20: ordinal not in range(256)
```

Fixing this is unfortunately somewhat complicated for a couple reasons:

1.) Users expect the output of `HTTPDigestAuth` to be a `str` in Python 3, changing that is likely breaking.
2.) If we were to encode the string, the libraries current convention would be `latin-1` not `utf-8`. That wouldn't solve this issue.

I don't believe we can ever format this correctly in Python 3 with the current behavior though. I'll need to look more tomorrow, but we may consider a behavior change if `self.username`/`self.password` is passed in as bytes.

**Comment by mubaldino** [comment]
Hi all, 
we encountered this week as we had a password policy change, too.  Unicode is now optional requirement for passwords.  But some may use it (I did...) and it broke twine, pip, and other things that would use `requests.auth` module for authentication.

I saw the exception above, and knew immediately a quick test to see if charset encoding would fix it:
```
    # requests/auth.py,   _basic_auth_str()
....
    if isinstance(password, str):
        # password = password.encode("latin1")
        password = password.encode("utf-8")            # Hey! IT works,... now just make it an optional kwarg
```

I realize exposing encoding in the function signatures will have a ripple effect, but I don't think the `latin1` assumption is all that great either. 

Requested change: add encoding kwarg to `_basic_auth_str()` and its consumers
```
def _basic_auth_str(username, passwd, encoding="latin1"):
   ...
   password = password.encode(encoding)
   ..
```

One line fix and I'm good to go.... hopefully you can include in an upcoming release.  Password policy changes are now more frequently including Unicode.

**Comment by abhii734** [comment]
I'd like to work on fixing this issue with non-latin credentials in HTTPDigestAuth.

**Comment by naarob** [comment]
Hi — I hit this bug recently and wrote a fix. I opened PR #7295 but it was closed, probably because it came from my fork's `main` branch (bad practice on my part) and without prior discussion here.

**The issue:** `build_digest_header` uses `f"{self.username}:{realm}:{self.password}"` directly. When credentials are bytes, Python formats them as `b'\xd0...'` instead of the decoded string, producing an invalid MD5/SHA hash.

**The fix** is straightforward — normalize to str before building A1 and the Authorization header:

```python
username = self.username.decode("utf-8") if isinstance(self.username, bytes) else self.username
password = self.password.decode("utf-8") if isinstance(self.password, bytes) else self.password
A1 = f"{username}:{realm}:{password}"
```

The fix is 12 lines in `auth.py`. Tests pass (238 assertions, 0 regressions). If the maintainers are open to a PR I'll open one from a proper feature branch this time.

**Comment by nateprewitt** [comment]
@naarob that's not the correct fix for this. It breaks the primary use case for build_digest_header. There's already a PR open with a potential fix.

**Comment by MeiSiristhebest** [comment]
Pushed a clean fix for this along with tests to my fork branch:
https://github.com/MeiSiristhebest/requests/commit/c686fee713305ac3a961e2aa518fd13da5abdf57

It normalizes credentials to `str` and uses `username*=UTF-8''` encoding for non-latin characters per RFC 7616 / RFC 5987 (while preserving standard `username="..."` for latin-1).

Since PRs are locked to collaborators here, feel free to pull `MeiSiristhebest:fix/digest-auth-nonlatin-username` if you'd like to merge it.

**Comment by yun520-1** [comment]
`HTTPDigestAuth` failing on non-Latin credentials is a charset-handling bug in the `uri` field computation, not a general Unicode problem. The digest `uri` must be the request-URI verbatim, including non-ASCII path segments, and the library should not coerce it to ASCII before hashing. The workaround in the issue (UTF-8 bytes) is correct but should not be necessary.

**Comment by LeonxLJX** [comment]
I'd like to take this one. The original #5089 was closed with the workaround 'encode credentials to UTF-8 bytes before passing them to `HTTPDigestAuth`' — that's a user-side band-aid, not a fix. The root cause is in `requests/auth.py` `HTTPDigestAuth.__init__` which stores the unicode strings, then in `build_digest_header` it does `username.encode('latin-1')` (forced by HTTP spec, RFC 7616 / RFC 2617) without first attempting UTF-8.

**Root cause.** In `requests/auth.py:HTTPDigestAuth.build_digest_header`, the digest computation uses `username:realm:password` hashed by `hashlib` over the bytes; the bytes are constructed with `latin-1` because HTTP Basic/Digest auth historically was latin-1 only. The bug: when the user passes a unicode string with non-latin chars (Cyrillic), `latin-1` encoding raises `UnicodeEncodeError`. The workaround was to pre-encode, which avoids the bug but loses the unicode clarity.

**Alternatives I considered:** (a) Detect the username chars, fall back to UTF-8 with `charset=utf-8` in the WWW-Authenticate (RFC 7616 modern digest auth) header (best IMO, conforms to modern spec). (b) Try latin-1 first, fall back to UTF-8 silently (the user's request is handled without error, but the server-side verification might fail). (c) Document that `HTTPDigestAuth` only supports latin-1 credentials (current behavior, unhelpful).

**Suggestion to maintainer:** (a) is the correct fix per RFC 7616. Two questions: (i) Does `requests` want to ship a `charset` parameter on `HTTPDigestAuth.__init__` (default `utf-8`)? (ii) For backwards compat with servers that reject the `charset=utf-8` qualifier in the WWW-Authenticate response, should we add a `force_latin1=True` opt-out? (claiming via @LeonxLJX)

**Comment by istoolsfox** [comment]
Hi, I've implemented a fix for this on my fork: https://github.com/istoolsfox/requests/tree/fix/digest-non-latin-credentials (commit 7d102ca)

**Root cause:** `build_digest_header` interpolates `self.username`/`self.password` into f-strings directly, so bytes credentials (the documented workaround from #5089) leak their Python repr — `username="b'Ond\xc5\x99ej'"` — and the response digest is computed over that garbage string, so it can never match the server's expectation.

**Core of the fix** — build the A1 octets explicitly instead of formatting credentials into a string:

```python
# str credentials: UTF-8 per RFC 7616 (unchanged behavior, byte-identical digests)
# bytes credentials: pre-encoded octets, used as-is
username_octets = (
    self.username.encode("utf-8")
    if isinstance(self.username, str)
    else self.username
)
password_octets = (
    self.password.encode("utf-8")
    if isinstance(self.password, str)
    else self.password
)
A1 = b":".join((username_octets, realm.encode("utf-8"), password_octets))
```

and decode bytes back to text only for header rendering:

```python
username = (
    self.username.decode("utf-8")
    if isinstance(self.username, bytes)
    else self.username
)
base = f'username="{username}", realm="{realm}", nonce="{nonce}", ...'
```

This follows the direction proposed in https://github.com/psf/requests/issues/6102#issuecomment-1087221857 ("we may consider a behavior change if `self.username`/`self.password` is passed in as bytes"). The `str` path is untouched.

**Tests:** added `tests/test_auth.py` (8 tests); the 5 bytes-related ones fail on unfixed `main`, all 8 pass with the fix. Full suite otherwise unchanged locally (Windows, Python 3.12): 637 passed / 3 skipped / 1 xfailed.

Since PR creation is limited to collaborators here, feel free to open the PR from `istoolsfox:fix/digest-non-latin-credentials`, or grant me access and I'll see it through review.
