### ISSUE TITLE
Headers that are subclass of str/byte are not accepted

### ISSUE THREAD

**Issue by CarliJoy** [psf/requests#6232]
Requests does not accept headers that are subclasses of string or byte.
They are required i.e. to obfuscate secrets in certain environments, so this is also a security related issue.

The issue was introduced by e36f34597ca96c40dbb81d63a8fe9ac0860b8dc3 at June this year by @nateprewitt 

A possible fix is given in this PR https://github.com/psf/requests/pull/6230

## Expected Result

Headers are used as they are string/byte.

## Actual Result
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib64/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/tmp/venv/lib64/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/tmp/venv/lib64/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/tmp/venv/lib64/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/tmp/venv/lib64/python3.10/site-packages/requests/models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "/tmp/venv/lib64/python3.10/site-packages/requests/models.py", line 491, in prepare_headers
    check_header_validity(header)
  File "/tmp/venv/lib64/python3.10/site-packages/requests/utils.py", line 1037, in check_header_validity
    raise InvalidHeader(
requests.exceptions.InvalidHeader: Header part (Hidden) from {'token': Hidden} must be of type str or bytes, not <class '__main__.Secret'>

```

## Reproduction Steps

```python
import requests

class Secret(str):
    def __repr__(self):
        return "Hidden"

requests.get("https://google.com", headers={"token": Secret("Confidential")})
```

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "2.1.1"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.3"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.6"
  },
  "platform": {
    "release": "5.19.6-100.fc35.x86_64",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.28.1"
  },
  "system_ssl": {
    "version": "1010111f"
  },
  "urllib3": {
    "version": "1.26.12"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

**Comment by nateprewitt** [comment]
Hi @CarliJoy, please check other open issues before opening new ones. I'll resolve this as a duplicate of #6159.

**Comment by CarliJoy** [comment]
Hi @nateprewitt and Sorry. Indeed I forgot to that. Sorry for the extra work.
