### ISSUE TITLE
ValueError: Timeout value connect was <object... under jenkins-job-builder exceptions after upgrade to 2.30.0

### ISSUE THREAD

**Issue by brackendawson** [psf/requests#6442]
Recent installations of jenkins-job-builder which use requests 2.30.0 fail.

Previously on 2.29.0 the same automation it was working.

## Actual Result
After the automation started picking 2.30.0 it installs but when ran it fails with this stack:
```
Traceback (most recent call last):
  File "/home/jenkins/.local/lib/python3.10/site-packages/jenkins/__init__.py", line 822, in get_info
    return json.loads(self.jenkins_open(
  File "/home/jenkins/.local/lib/python3.10/site-packages/jenkins/__init__.py", line 560, in jenkins_open
    return self.jenkins_request(req, add_crumb, resolve_auth).text
  File "/home/jenkins/.local/lib/python3.10/site-packages/jenkins/__init__.py", line 576, in jenkins_request
    self.maybe_add_crumb(req)
  File "/home/jenkins/.local/lib/python3.10/site-packages/jenkins/__init__.py", line 373, in maybe_add_crumb
    response = self.jenkins_open(requests.Request(
  File "/home/jenkins/.local/lib/python3.10/site-packages/jenkins/__init__.py", line 560, in jenkins_open
    return self.jenkins_request(req, add_crumb, resolve_auth).text
  File "/home/jenkins/.local/lib/python3.10/site-packages/jenkins/__init__.py", line 579, in jenkins_request
    self._request(req))
  File "/home/jenkins/.local/lib/python3.10/site-packages/jenkins/__init__.py", line 553, in _request
    return self._session.send(r, **_settings)
  File "/home/jenkins/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/jenkins/.local/lib/python3.10/site-packages/requests/adapters.py", line 483, in send
    timeout = TimeoutSauce(connect=timeout, read=timeout)
  File "/home/jenkins/.local/lib/python3.10/site-packages/urllib3/util/timeout.py", line 119, in __init__
    self._connect = self._validate_timeout(connect, "connect")
  File "/home/jenkins/.local/lib/python3.10/site-packages/urllib3/util/timeout.py", line 156, in _validate_timeout
    raise ValueError(
ValueError: Timeout value connect was <object object at 0x7f1d409a08b0>, but it must be an int, float or None.

During handling of the above exception, another exception occurred:

... the same stack repeated about 650 times ...
```

## Reproduction Steps

1. Install Python 3.10 on Linux
2. Install jenkins-job-builder 5.0.2
3. Use jenkins job builder to configure jobs in a jenkins instance.

Sorry, this is very involved, I'm working on a reduced recreate.

## System Information

    $ python -m requests.help

```json
{
  "chardet": {
    "version": null
  },
  "charset_normalizer": {
    "version": "3.1.0"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "3.4"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.10.10"
  },
  "platform": {
    "release": "5.4.0-139-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.30.0"
  },
  "system_ssl": {
    "version": "1010106f"
  },
  "urllib3": {
    "version": "2.0.2"
  },
  "using_charset_normalizer": true,
  "using_pyopenssl": false
}
```

I suspect this might be related to #6432

**Comment by sigmavirus24** [comment]
I suspect something in `**_settings` in this line in your stack trace is part of the issue: 

```
    return self._session.send(r, **_settings)
```

The line right before it [sets the timeout](https://opendev.org/jjb/python-jenkins/src/commit/70dc3e4f711088e0cc9f0a92706fee3cb0757bac/jenkins/__init__.py#L552). That value defaults to `socket._GLOBAL_DEFAULT_TIMEOUT` which locally looks like this to me:

```
~ ❯ python -c 'import socket; print(socket._GLOBAL_DEFAULT_TIMEOUT)'
<object object at 0x7faa71f88430>
```

So I'm guessing that's the source of `object object` for you. We pass whatever timeout the user gives us to urllib3. So this may be a thing to ask there. Regardless, I don't think _anyone_ should be using private sentinel values

**Comment by brackendawson** [comment]
Thanks, the issue seems to have already been reported here: https://bugs.launchpad.net/python-jenkins/+bug/2018567
