### ISSUE TITLE
'parse_authorization_header' not found in werkzeug 3.0.0

### ISSUE THREAD

**Issue by psriram4** [psf/requests#6541]
I run in to the following error:

`ImportError: cannot import name 'parse_authorization_header' from 'werkzeug.http' (/usr/local/lib/python3.9/site-packages/werkzeug/http.py)`.

## Reproduction Steps

```
pip install -r requirements_dev.txt

```

I'm able to resolve it if I downgrade werkzeug to a lower version (2.3.7). I think this needs to be accounted for in the dependencies or code.

**Comment by sigmavirus24** [comment]
This does not seem to be a bug with requests as we do not rely on werkzeug. Please file this in a more appropriate place with much more detail for that project to be able to help you

**Comment by bruceadams** [comment]
I hit this problem on MacOS 14.1.1.

In this example, I'm running Python 3.9.16. I saw the same failure on 3.11.4 on a different Mac.

In a fresh checkout:

```
% python -m venv venv
% source venv/bin/activate
% make
. . . no failure here . . .
% make ci
python -m pytest tests --junitxml=report.xml
Traceback (most recent call last):
  File "/Users/bruce/.pyenv/versions/3.9.16/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/bruce/.pyenv/versions/3.9.16/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/bruce/github/requests/venv/lib/python3.9/site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File "/Users/bruce/github/requests/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/Users/bruce/github/requests/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/Users/bruce/github/requests/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/Users/bruce/github/requests/venv/lib/python3.9/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/Users/bruce/github/requests/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/bruce/github/requests/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 130, in _multicall
    teardown[0].send(outcome)
  File "/Users/bruce/github/requests/venv/lib/python3.9/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/Users/bruce/github/requests/venv/lib/python3.9/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/Users/bruce/github/requests/venv/lib/python3.9/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/Users/bruce/github/requests/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/bruce/github/requests/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/bruce/github/requests/venv/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1172, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/Users/bruce/github/requests/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 398, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/Users/bruce/.pyenv/versions/3.9.16/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/Users/bruce/.pyenv/versions/3.9.16/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/Users/bruce/github/requests/venv/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/Users/bruce/github/requests/venv/lib/python3.9/site-packages/pytest_httpbin/plugin.py", line 2, in <module>
    from httpbin import app as httpbin_app
  File "/Users/bruce/github/requests/venv/lib/python3.9/site-packages/httpbin/__init__.py", line 3, in <module>
    from .core import *
  File "/Users/bruce/github/requests/venv/lib/python3.9/site-packages/httpbin/core.py", line 35, in <module>
    from werkzeug.http import parse_authorization_header
ImportError: cannot import name 'parse_authorization_header' from 'werkzeug.http' (/Users/bruce/github/requests/venv/lib/python3.9/site-packages/werkzeug/http.py)
make: *** [ci] Error 1
```

**Comment by sigmavirus24** [comment]
@bruceadams the issue is with a test dependent, not requests

**Comment by bruceadams** [comment]
For anyone who hits this problem in the future, a workaround is to add the entry `werkzeug<3.0.0` into `requirements-dev.txt`. With this addition, running requests unit tests works.

```bash
echo 'werkzeug<3.0.0' >> requirements-dev.txt
make
make ci
```

My wild guess is this problem is specific to Mac's with Apple Silicon, since `make && make ci` appears to run fine on [macOS on GitHub Actions](https://github.com/psf/requests/blob/main/.github/workflows/run-tests.yml).
