### ISSUE TITLE
catch FileNotFoundError if there aren't any certificates

### ISSUE THREAD

**Issue by eaglegai** [psf/requests#6749]
I set verify to False, but it still need cerfiticate
As we have catched ImportError, why not catch FileNotFoundError together?
## Expected Result
won't Traceback

## Actual Result
```
[root@localhost requests]# ./test-requests.py
Traceback (most recent call last):
  File "/root/test/requests/./test-requests.py", line 2, in <module>
    import requests
  File "/usr/lib/python3.9/site-packages/requests/__init__.py", line 136, in <module>
    from .api import request, get, head, post, patch, put, delete, options
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 13, in <module>
    from . import sessions
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 28, in <module>
    from .adapters import HTTPAdapter
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 65, in <module>
    _preloaded_ssl_context.load_verify_locations(
FileNotFoundError: [Errno 2] No such file or directory
```
[root@localhost requests]#

## Reproduction Steps
```
#!/usr/bin/python3
import requests
r = requests.get("http://127.0.0.1",verify=False)
print(r.text)
```
```python
import requests

```

## System Information

    $ python -m requests.help

```json
{
  "paste": "here"
}
```

**Comment by nateprewitt** [comment]
Hi @eaglegai, `certifi` is a [declared dependency](https://github.com/psf/requests/blob/0e322af87745eff34caffe4df68456ebc20d9068/setup.py#L65) of Requests. This should be available in all installations. We derive the the [`DEFAULT_CA_BUNDLE_PATH`](https://github.com/psf/requests/blob/0e322af87745eff34caffe4df68456ebc20d9068/src/requests/utils.py#L63) being used in this line from `requests.certs.where()`.

Can you confirm you 1.) have `certifi` installed and 2.) the value of `import requests; requests.certs.where()`?

**Comment by Lu655** [comment]
> Hi @eaglegai, `certifi` is a [declared dependency](https://github.com/psf/requests/blob/0e322af87745eff34caffe4df68456ebc20d9068/setup.py#L65) of Requests. This should be available in all installations. We derive the the [`DEFAULT_CA_BUNDLE_PATH`](https://github.com/psf/requests/blob/0e322af87745eff34caffe4df68456ebc20d9068/src/requests/utils.py#L63) being used in this line from `requests.certs.where()`.
> 
> Can you confirm you 1.) have `certifi` installed and 2.) the value of `import requests; requests.certs.where()`?
Hi @eaglegai I also have the problem as you said. When will be solved?

**Comment by eaglegai** [comment]
Hi @nateprewitt , we build a mini environment which cut off the unnecessary packages,
and in this env, we just `import requests `for `http://` and `verify is false` is enough.
It's not reasonable to force to load the certificates by default, because it's not necessary in the case that verify is false.

As we consider the case that isn't built with the ssl module, why not consider the situation that 'verify is false' needn't certificates.

**Comment by nateprewitt** [comment]
This code path no longer exists in Requests.
